# Generated by Django 5.2.10 on 2026-01-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_chats', models.IntegerField(default=50, verbose_name='Максимум чатов')),
                ('current_chats', models.IntegerField(default=0, verbose_name='Текущее количество чатов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аккаунта')),
                ('account_type', models.CharField(choices=[('personal', 'Личный аккаунт (Hydrogram)'), ('bot', 'Бот (pyTelegramBotAPI)')], max_length=20, verbose_name='Тип аккаунта')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('authenticating', 'Авторизация'), ('error', 'Ошибка')], default='inactive', max_length=20, verbose_name='Статус')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона')),
                ('api_id', models.BigIntegerField(blank=True, null=True, verbose_name='API ID')),
                ('api_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Hash')),
                ('session_string', models.TextField(blank=True, help_text='StringSession для Hydrogram', null=True)),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Bot Token')),
                ('bot_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username бота')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL для webhook')),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telegram Аккаунт',
                'verbose_name_plural': 'Telegram Аккаунты',
                'indexes': [models.Index(fields=['status', 'account_type'], name='crm_app_tel_status_5c46bd_idx'), models.Index(fields=['telegram_user_id'], name='crm_app_tel_telegra_a94ebd_idx'), models.Index(fields=['created_at'], name='crm_app_tel_created_373922_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram Chat ID')),
                ('chat_type', models.CharField(choices=[('private', 'Личный чат'), ('group', 'Группа'), ('supergroup', 'Супергруппа'), ('channel', 'Канал')], max_length=20, verbose_name='Тип чата')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('telegram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='crm_app.telegramaccount', verbose_name='Telegram Аккаунт')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram Message ID')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('voice', 'Голосовое'), ('document', 'Документ'), ('sticker', 'Стикер'), ('location', 'Локация'), ('contact', 'Контакт'), ('other', 'Другое')], default='text', max_length=20, verbose_name='Тип сообщения')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('sent', 'Отправлено'), ('pending', 'Ожидает отправки'), ('failed', 'Ошибка отправки')], default='received', max_length=20, verbose_name='Статус')),
                ('text', models.TextField(blank=True, null=True)),
                ('from_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('from_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_user_username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_outgoing', models.BooleanField(db_index=True, default=False, verbose_name='Исходящее')),
                ('media_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('media_caption', models.TextField(blank=True, null=True)),
                ('telegram_date', models.DateTimeField(db_index=True, verbose_name='Дата в Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm_app.chat', verbose_name='Чат')),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='crm_app.message')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-telegram_date'],
                'indexes': [models.Index(fields=['chat', 'telegram_date'], name='crm_app_mes_chat_id_8952e9_idx'), models.Index(fields=['chat', 'is_outgoing', 'telegram_date'], name='crm_app_mes_chat_id_d881ca_idx'), models.Index(fields=['from_user_id', 'telegram_date'], name='crm_app_mes_from_us_9596df_idx'), models.Index(fields=['status', 'created_at'], name='crm_app_mes_status_696376_idx'), models.Index(fields=['message_type'], name='crm_app_mes_message_8100ce_idx')],
                'unique_together': {('telegram_id', 'chat')},
            },
        ),
        migrations.CreateModel(
            name='ChatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='crm_app.chat', verbose_name='Чат')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_chats', to='crm_app.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Назначение чата',
                'verbose_name_plural': 'Назначения чатов',
                'indexes': [models.Index(fields=['operator', 'is_active', 'assigned_at'], name='crm_app_cha_operato_39dd2a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['telegram_account', 'last_message_at'], name='crm_app_cha_telegra_fe8048_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['chat_type', 'last_message_at'], name='crm_app_cha_chat_ty_52d8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['created_at'], name='crm_app_cha_created_1e9cda_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['telegram_account', 'unread_count', 'last_message_at'], name='crm_app_cha_telegra_c8e162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('telegram_id', 'telegram_account')},
        ),
    ]
