# Generated by Django 5.2.10 on 2026-01-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='webhook_url',
        ),
    ]
