# Generated by Django 5.2.10 on 2026-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_remove_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_code_sent_at',
            field=models.DateTimeField(blank=True, help_text='Время отправки OTP', null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_code_type',
            field=models.CharField(blank=True, help_text='Тип OTP (SMS/APP/CALL/FLASH_CALL)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_phone_code_hash',
            field=models.CharField(blank=True, help_text='Хэш кода подтверждения (OTP)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_session_string',
            field=models.TextField(blank=True, help_text='Временная StringSession для этапа отправки OTP', null=True),
        ),
    ]
