# Generated by Django 5.2.10 on 2026-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_add_pending_otp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='pending_session_name',
            field=models.CharField(blank=True, help_text='Имя временной сессии для OTP (файловая сессия)', max_length=255, null=True),
        ),
    ]
