# Generated by Django 5.2.10 on 2026-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_add_pending_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='telegram_file_id',
            field=models.CharField(blank=True, help_text='Telegram file ID для повторного скачивания', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Личный аккаунт (Telethon)'), ('bot', 'Бот (pyTelegramBotAPI)')], max_length=20, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='session_string',
            field=models.TextField(blank=True, help_text='StringSession для Telethon', null=True),
        ),
    ]
