# Generated by Django 5.2.10 on 2026-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_provider_integrations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_external_message_per_chat',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('chat', 'external_message_id'), name='unique_external_message_per_chat'),
        ),
    ]
