# Generated by Django 5.2.10 on 2026-08-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_telegramaccount_restart_requested_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Аккаунт мессенджера', 'verbose_name_plural': 'Аккаунты мессенджеров'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='telegram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='crm_app.telegramaccount', verbose_name='Аккаунт мессенджера'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, verbose_name='ID чата у провайдера'),
        ),
        migrations.AlterField(
            model_name='message',
            name='telegram_date',
            field=models.DateTimeField(db_index=True, verbose_name='Дата сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID сообщения у провайдера'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Telegram — личный аккаунт'), ('bot', 'Telegram — бот'), ('whatsapp', 'WhatsApp через GREEN-API'), ('max', 'MAX — личный аккаунт через GREEN-API')], max_length=20, verbose_name='Тип аккаунта'),
        ),
    ]
