# Generated by Django 5.1.7 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_historyimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Telegram — личный аккаунт'), ('bot', 'Telegram — бот'), ('whatsapp', 'WhatsApp через GREEN-API'), ('max', 'MAX — личный аккаунт через GREEN-API')], help_text='Определяет мессенджер и способ подключения. После создания не изменяется.', max_length=20, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя профиля'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия профиля'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='session_string',
            field=models.TextField(blank=True, help_text='Создаётся автоматически после успешной авторизации. Вручную не заполняется.', null=True, verbose_name='Сессия Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('authenticating', 'Авторизация'), ('error', 'Ошибка')], default='inactive', help_text='Устанавливается CRM автоматически; для запуска и остановки используйте действия над аккаунтом.', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Определяется автоматически после подключения.', null=True, verbose_name='ID пользователя Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Username профиля'),
        ),
    ]
