# Generated by Django 5.1.7 on 2026-08-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_aisettings_googlecontact_chat_ai_paused_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='max_incoming_age_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Не отвечать на сообщения старше, минут'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='operator_idle_seconds',
            field=models.PositiveIntegerField(default=90, verbose_name='Считать администратора неактивным через, секунд'),
        ),
        migrations.AddField(
            model_name='operatorpresencesession',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
