# Generated by Django 5.1.7 on 2026-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_aisettings_max_incoming_age_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorpresencesession',
            name='inactive_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
